rabindranathfv/arbitraje_asovac

teg_asovac_src/core_app/urls.py, teg_asovac_src/main_app/forms.py, teg_asovac_src/main_app/urls.py, teg_asovac_src/main_app/views.py, teg_asovac_src/static_pro/static/css/base_style.css, teg_asovac_src/static_pro/static/js/asovac_script.js, teg_asovac_src/templates/base.html, teg_asovac_src/templates/base_users.html, teg_asovac_src/templates/footer.html, teg_asovac_src/templates/home.html, teg_asovac_src/templates/js_scripts.html, teg_asovac_src/templates/login.html
=> Production Features from Dev

teg_asovac_src/static_pro/static/css/base_style.css, teg_asovac_src/templates/home.html
Update into Dev from Teg 32 crear home
=> Update into Dev from Teg 32 crear home

teg_asovac_src/main_app/models.py
=> Fix register like autor

teg_asovac_src/arbitrajes/views.py, teg_asovac_src/autores/views.py, teg_asovac_src/eventos/views.py, teg_asovac_src/main_app/views.py, teg_asovac_src/recursos/views.py, teg_asovac_src/sesiones/views.py, teg_asovac_src/templates/base.html, teg_asovac_src/templates/main_app_home.html, teg_asovac_src/templates/sidebar.html, teg_asovac_src/trabajos/views.py
=> Using sessions

teg_asovac_src/autores/forms.py, teg_asovac_src/autores/views.py, teg_asovac_src/main_app/forms.py, teg_asovac_src/main_app/views.py, teg_asovac_src/static_pro/static/js/asovac_script.js, teg_asovac_src/templates/ajax/author_create_autor_modal.html, teg_asovac_src/templates/ajax/changepassword_modal.html, teg_asovac_src/templates/ajax/edit_own_author.html
=> Merge from TEG62 to estable

teg_asovac_src/eventos/forms.py, teg_asovac_src/eventos/views.py, teg_asovac_src/static_pro/static/js/asovac_script.js, teg_asovac_src/templates/ajax/add_organizer_to_event.html, teg_asovac_src/templates/eventos_event_create.html, teg_asovac_src/templates/eventos_event_edit.html, teg_asovac_src/templates/eventos_event_list.html, teg_asovac_src/templates/eventos_organizer_create.html, teg_asovac_src/templates/eventos_organizer_list.html
=> Merge from Teg65 to develop

teg_asovac_src/static_pro/static/js/grid.js, teg_asovac_src/templates/ajax/BTTrabajos.html, teg_asovac_src/templates/email_templates/create_invitation.html, teg_asovac_src/templates/email_templates/create_invitation.txt, teg_asovac_src/templates/email_templates/email_base_template.html, teg_asovac_src/templates/trabajos_invitation.html, teg_asovac_src/trabajos/tokens.py, teg_asovac_src/trabajos/urls.py, teg_asovac_src/trabajos/views.py
=> Merge from develop to TEG61

teg_asovac_src/arbitrajes/views.py, teg_asovac_src/autores/views.py, teg_asovac_src/core_app/settings.py, teg_asovac_src/eventos/views.py, teg_asovac_src/main_app/views.py, teg_asovac_src/recursos/views.py, teg_asovac_src/seguimiento/views.py, teg_asovac_src/sesiones/views.py, teg_asovac_src/trabajos/views.py
Merge branch to 'develop' from 'Teg-46_aplicar_decorator_login_required'
=> Teg 46 aplicar decorator login required

teg_asovac_src/autores/urls.py, teg_asovac_src/autores/views.py, teg_asovac_src/templates/autores_postular_trabajo.html, teg_asovac_src/templates/base.html, teg_asovac_src/templates/trabajos.html
Merge from 'Teg81 integrar contenido postular trabajo' to 'develop'
=> Merge from 'Teg81 integrar contenido postular trabajo' to 'develop'

teg_asovac_src/autores/views.py, teg_asovac_src/core_app/settings.py, teg_asovac_src/templates/autores_postular_trabajo.html, teg_asovac_src/templates/trabajos.html, teg_asovac_src/trabajos/views.py
Merge from TEG82-Carga_de_trabajos to develop
=> Merge from TEG82-Carga_de_trabajos to develop

teg_asovac_src/sesiones/views.py, teg_asovac_src/templates/email_templates/coordinator_assign.html, teg_asovac_src/templates/email_templates/coordinator_assign.txt
=> Merge TEG58 to develop

teg_asovac_src/autores/forms.py, teg_asovac_src/autores/models.py, teg_asovac_src/autores/views.py, teg_asovac_src/main_app/views.py, teg_asovac_src/templates/trabajos.html, teg_asovac_src/trabajos/views.py
Merge from TEG85-Correcciones to develop
=> Merge from TEG85-Correcciones to develop

teg_asovac_src/core_app/settings.py, teg_asovac_src/recursos/urls.py, teg_asovac_src/recursos/views.py, teg_asovac_src/templates/base.html, teg_asovac_src/templates/js_scripts.html, teg_asovac_src/templates/recursos.html
Merge from TEG52-Exportar_resultados to develop
=> Merge from TEG52-Exportar_resultados to develop

teg_asovac_src/recursos/views.py, teg_asovac_src/templates/recursos.html
Merge from TEG83-Grafico_autores_area to develop
=> Merge from TEG83-Grafico_autores_area to develop

teg_asovac_src/main_app/views.py, teg_asovac_src/templates/main_app_data_basic.html
Merge from TEG88-Desactivar_botones_contrasenas to develop
=> Merge from TEG88-Desactivar_botones_contrasenas to develop

teg_asovac_src/recursos/views.py, teg_asovac_src/templates/recursos.html
Merge from TEG91-Resultados_n_areas intoto TEG-98
=> Merge from TEG91-Resultados_n_areas intoto TEG-98

teg_asovac_src/recursos/views.py, teg_asovac_src/templates/recursos.html
Merge from TEG91-Resultados_n_areas to develop
=> Merge from TEG91-Resultados_n_areas to develop

teg_asovac_src/autores/urls.py, teg_asovac_src/autores/views.py, teg_asovac_src/templates/autores_authors_list.html
Merge from TEG107-Ejemplos_import_autores into develop
=> Merge from TEG107-Ejemplos_import_autores into develop

teg_asovac_src/templates/autores_postular_trabajo.html, teg_asovac_src/templates/trabajos_trabajo_pago.html, teg_asovac_src/trabajos/forms.py, teg_asovac_src/trabajos/views.py
Merge from Teg121 fix front pagos into develop
=> Merge from Teg121 fix front pagos into develop

teg_asovac_src/core_app/urls.py, teg_asovac_src/main_app/views.py
Merge from TEG121_Login_validation into develop
=> Merge from TEG121_Login_validation into develop

teg_asovac_src/main_app/forms.py, teg_asovac_src/main_app/views.py, teg_asovac_src/templates/main_app_status_arbitration.html
Merge from Teg122 fix basic flux into develop
=> Merge from Teg122 fix basic flux into develop

teg_asovac_src/recursos/forms.py, teg_asovac_src/recursos/views.py, teg_asovac_src/templates/email_templates/certificate.html, teg_asovac_src/templates/main_app_resources_author.html
Merge from Teg86 certificado autores into develop
=> Merge from Teg86 certificado autores into develop

teg_asovac_src/main_app/views.py, teg_asovac_src/templates/main_app_status_arbitration.html
- changing the place where form errors and success mesages get displayed in the
template.
- Adding a success message to the change of status of a Sistema_asovac.
=> Add success message to the change of status of a Sistema_asovac

teg_asovac_src/autores/views.py, teg_asovac_src/sesiones/views.py, teg_asovac_src/templates/ajax/postular_trabajo_datos_pagador.html, teg_asovac_src/templates/arbitrajes_jobs_for_review.html, teg_asovac_src/templates/sesiones_create_sesion.html, teg_asovac_src/trabajos/views.py
Merge from Teg130 errores mensajes into develop
=> Merge from Teg130 errores mensajes into develop

teg_asovac_src/arbitrajes/models.py, teg_asovac_src/main_app/forms.py, teg_asovac_src/main_app/urls.py, teg_asovac_src/main_app/views.py, teg_asovac_src/templates/ajax/edit_personal_data.html, teg_asovac_src/templates/base.html
Merge from Teg126 editar datos personales into develop
=> Merge from Teg126 editar datos personales into develop

teg_asovac_src/templates/trabajos.html, teg_asovac_src/templates/trabajos_edit_trabajo.html
Merge from Teg179 problemas ajax modals trabajos into develop
=> Merge from Teg179 problemas ajax modals trabajos into develop

teg_asovac_src/arbitrajes/views.py, teg_asovac_src/static_pro/static/css/base_style.css, teg_asovac_src/templates/ajax/BTTrabajos.html, teg_asovac_src/templates/base.html, teg_asovac_src/trabajos/views.py
Merge from Teg187 sin arbitros asignados into develop
=> Merge from Teg187 sin arbitros asignados into develop

teg_asovac_src/main_app/forms.py, teg_asovac_src/main_app/views.py, teg_asovac_src/static_pro/static/js/asovac_script.js, teg_asovac_src/templates/main_app_home.html
Merge from Teg191 minor fixs into develop
=> Merge from Teg191 minor fixs into develop
